notebook-docs:
	IS_GENERATING_DOCS=true uv run jupyter nbconvert docs/notebooks/*.ipynb \
		--config jupyter_nbconvert_config.py \
		--NbConvertApp.output_files_dir notebook-assets \
		--to markdown

notebook-debug-scriptify:
	IS_GENERATING_DOCS=true uv run jupyter nbconvert docs/notebooks/*.ipynb \
		--output-dir docs/notebooks-autogenerated \
		--NbConvertApp.output_files_dir notebook-assets \
		--to script

serve:
	uv run mkdocs serve

build:
	uv run mkdocs build
